package com.dmd.letutors.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUBJECT.
 */
public class Subject {

    private Long id;
    private String imgUrl;
    private String subjectLevel_id;
    private String hot;
    private String subjectName;

    public Subject() {
    }

    public Subject(Long id) {
        this.id = id;
    }

    public Subject(Long id, String imgUrl, String subjectLevel_id, String hot, String subjectName) {
        this.id = id;
        this.imgUrl = imgUrl;
        this.subjectLevel_id = subjectLevel_id;
        this.hot = hot;
        this.subjectName = subjectName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getSubjectLevel_id() {
        return subjectLevel_id;
    }

    public void setSubjectLevel_id(String subjectLevel_id) {
        this.subjectLevel_id = subjectLevel_id;
    }

    public String getHot() {
        return hot;
    }

    public void setHot(String hot) {
        this.hot = hot;
    }

    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

}
