package com.dmd.letutors.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUBJECTLEVEL.
 */
public class Subjectlevel {

    private Long id;
    /** Not-null value. */
    private String subjectLevelName;

    public Subjectlevel() {
    }

    public Subjectlevel(Long id) {
        this.id = id;
    }

    public Subjectlevel(Long id, String subjectLevelName) {
        this.id = id;
        this.subjectLevelName = subjectLevelName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSubjectLevelName() {
        return subjectLevelName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSubjectLevelName(String subjectLevelName) {
        this.subjectLevelName = subjectLevelName;
    }

}
