package com.dmd.letutors.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dmd.letutors.bean.Subject;
import com.dmd.letutors.bean.Subjectlevel;

import com.dmd.letutors.dao.SubjectDao;
import com.dmd.letutors.dao.SubjectlevelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subjectDaoConfig;
    private final DaoConfig subjectlevelDaoConfig;

    private final SubjectDao subjectDao;
    private final SubjectlevelDao subjectlevelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subjectDaoConfig = daoConfigMap.get(SubjectDao.class).clone();
        subjectDaoConfig.initIdentityScope(type);

        subjectlevelDaoConfig = daoConfigMap.get(SubjectlevelDao.class).clone();
        subjectlevelDaoConfig.initIdentityScope(type);

        subjectDao = new SubjectDao(subjectDaoConfig, this);
        subjectlevelDao = new SubjectlevelDao(subjectlevelDaoConfig, this);

        registerDao(Subject.class, subjectDao);
        registerDao(Subjectlevel.class, subjectlevelDao);
    }
    
    public void clear() {
        subjectDaoConfig.getIdentityScope().clear();
        subjectlevelDaoConfig.getIdentityScope().clear();
    }

    public SubjectDao getSubjectDao() {
        return subjectDao;
    }

    public SubjectlevelDao getSubjectlevelDao() {
        return subjectlevelDao;
    }

}
